//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Theme {
    
    private ThemeElements elementsField;
    
    private ThemeSeparators separatorsField;
    
    private ThemeEffects effectsField;
    
    /// <remarks/>
    public ThemeElements Elements {
        get {
            return this.elementsField;
        }
        set {
            this.elementsField = value;
        }
    }
    
    /// <remarks/>
    public ThemeSeparators Separators {
        get {
            return this.separatorsField;
        }
        set {
            this.separatorsField = value;
        }
    }
    
    /// <remarks/>
    public ThemeEffects Effects {
        get {
            return this.effectsField;
        }
        set {
            this.effectsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElements {
    
    private ThemeElementsOutput outputField;
    
    private ThemeElementsActors actorsField;
    
    private ThemeElementsGenres genresField;
    
    private ThemeElementsRating ratingField;
    
    private ThemeElementsTitle titleField;
    
    private ThemeElementsTagLine tagLineField;
    
    private ThemeElementsOriginalTitle originalTitleField;
    
    private ThemeElementsRuntime runtimeField;
    
    private ThemeElementsDescription descriptionField;
    
    private ThemeElementsRelaeseDate relaeseDateField;
    
    private ThemeElementsSeason seasonField;
    
    private ThemeElementsBackground backgroundField;
    
    private ThemeElementsCover coverField;
    
    /// <remarks/>
    public ThemeElementsOutput Output {
        get {
            return this.outputField;
        }
        set {
            this.outputField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsActors Actors {
        get {
            return this.actorsField;
        }
        set {
            this.actorsField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsGenres Genres {
        get {
            return this.genresField;
        }
        set {
            this.genresField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsRating Rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsTitle Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsTagLine TagLine {
        get {
            return this.tagLineField;
        }
        set {
            this.tagLineField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsOriginalTitle OriginalTitle {
        get {
            return this.originalTitleField;
        }
        set {
            this.originalTitleField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsRuntime Runtime {
        get {
            return this.runtimeField;
        }
        set {
            this.runtimeField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsDescription Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsRelaeseDate RelaeseDate {
        get {
            return this.relaeseDateField;
        }
        set {
            this.relaeseDateField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsSeason Season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsBackground Background {
        get {
            return this.backgroundField;
        }
        set {
            this.backgroundField = value;
        }
    }
    
    /// <remarks/>
    public ThemeElementsCover Cover {
        get {
            return this.coverField;
        }
        set {
            this.coverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsOutput {
    
    private ushort heightField;
    
    private ushort widthField;
    
    private string formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsActors {
    
    private bool visibleField;
    
    private string separatorField;
    
    private byte maximumValuesField;
    
    private string orientationField;
    
    private bool displayPicField;
    
    private ushort picHeightField;
    
    private ushort picWidthField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Separator {
        get {
            return this.separatorField;
        }
        set {
            this.separatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MaximumValues {
        get {
            return this.maximumValuesField;
        }
        set {
            this.maximumValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool displayPic {
        get {
            return this.displayPicField;
        }
        set {
            this.displayPicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort picHeight {
        get {
            return this.picHeightField;
        }
        set {
            this.picHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort picWidth {
        get {
            return this.picWidthField;
        }
        set {
            this.picWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsGenres {
    
    private bool visibleField;
    
    private string separatorField;
    
    private byte maximumValuesField;
    
    private string orientationField;
    
    private bool displayPicField;
    
    private ushort picHeightField;
    
    private ushort picWidthField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Separator {
        get {
            return this.separatorField;
        }
        set {
            this.separatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MaximumValues {
        get {
            return this.maximumValuesField;
        }
        set {
            this.maximumValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool displayPic {
        get {
            return this.displayPicField;
        }
        set {
            this.displayPicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort picHeight {
        get {
            return this.picHeightField;
        }
        set {
            this.picHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort picWidth {
        get {
            return this.picWidthField;
        }
        set {
            this.picWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsRating {
    
    private bool visibleField;
    
    private bool displayPicField;
    
    private string picPathField;
    
    private byte picHeightField;
    
    private byte picWidthField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool displayPic {
        get {
            return this.displayPicField;
        }
        set {
            this.displayPicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string picPath {
        get {
            return this.picPathField;
        }
        set {
            this.picPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte picHeight {
        get {
            return this.picHeightField;
        }
        set {
            this.picHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte picWidth {
        get {
            return this.picWidthField;
        }
        set {
            this.picWidthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsTitle {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsTagLine {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsOriginalTitle {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsRuntime {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsDescription {
    
    private bool visibleField;
    
    private byte heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsRelaeseDate {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsSeason {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string fontNameField;
    
    private byte fontSizeField;
    
    private bool fontBoldField;
    
    private int foreColorField;
    
    private string titleField;
    
    private int titleForeColorField;
    
    private ushort titleVerticalPosField;
    
    private ushort titleHorisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fontName {
        get {
            return this.fontNameField;
        }
        set {
            this.fontNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte fontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fontBold {
        get {
            return this.fontBoldField;
        }
        set {
            this.fontBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int foreColor {
        get {
            return this.foreColorField;
        }
        set {
            this.foreColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int titleForeColor {
        get {
            return this.titleForeColorField;
        }
        set {
            this.titleForeColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleVerticalPos {
        get {
            return this.titleVerticalPosField;
        }
        set {
            this.titleVerticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort titleHorisontalPos {
        get {
            return this.titleHorisontalPosField;
        }
        set {
            this.titleHorisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsBackground {
    
    private bool visibleField;
    
    private bool useItemBackgroundField;
    
    private string defaultBackgroundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool useItemBackground {
        get {
            return this.useItemBackgroundField;
        }
        set {
            this.useItemBackgroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultBackground {
        get {
            return this.defaultBackgroundField;
        }
        set {
            this.defaultBackgroundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeElementsCover {
    
    private bool visibleField;
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string defaultCoverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool visible {
        get {
            return this.visibleField;
        }
        set {
            this.visibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultCover {
        get {
            return this.defaultCoverField;
        }
        set {
            this.defaultCoverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeSeparators {
    
    private ThemeSeparatorsImage[] imageField;
    
    private ThemeSeparatorsRectangle[] rectangleField;
    
    private ThemeSeparatorsLine[] lineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Image")]
    public ThemeSeparatorsImage[] Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rectangle")]
    public ThemeSeparatorsRectangle[] Rectangle {
        get {
            return this.rectangleField;
        }
        set {
            this.rectangleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public ThemeSeparatorsLine[] Line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeSeparatorsImage {
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private string opacityField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Opacity {
        get {
            return this.opacityField;
        }
        set {
            this.opacityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeSeparatorsRectangle {
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    private int solidBrushColorField;
    
    private int linearGradientBrushColor1Field;
    
    private int linearGradientBrushColor2Field;
    
    private string linearGradientBrushDirectionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SolidBrushColor {
        get {
            return this.solidBrushColorField;
        }
        set {
            this.solidBrushColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int LinearGradientBrushColor1 {
        get {
            return this.linearGradientBrushColor1Field;
        }
        set {
            this.linearGradientBrushColor1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int LinearGradientBrushColor2 {
        get {
            return this.linearGradientBrushColor2Field;
        }
        set {
            this.linearGradientBrushColor2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LinearGradientBrushDirection {
        get {
            return this.linearGradientBrushDirectionField;
        }
        set {
            this.linearGradientBrushDirectionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeSeparatorsLine {
    
    private ushort heightField;
    
    private ushort widthField;
    
    private ushort verticalPosField;
    
    private ushort horisontalPosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort verticalPos {
        get {
            return this.verticalPosField;
        }
        set {
            this.verticalPosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort horisontalPos {
        get {
            return this.horisontalPosField;
        }
        set {
            this.horisontalPosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeEffects {
    
    private ThemeEffectsEffect effectField;
    
    /// <remarks/>
    public ThemeEffectsEffect Effect {
        get {
            return this.effectField;
        }
        set {
            this.effectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ThemeEffectsEffect {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
